name: Update requirements.txt

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main  # Replace with your default branch if different
permissions:
  contents: write  # Allows the workflow to push changes
  
jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'  # Specify your Python version

      # Step 3: Install pipreqs
      - name: Install pipreqs
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs

      # Step 4: Generate requirements.txt
      - name: Generate requirements.txt
        run: |
          pipreqs . --force  # The --force flag overwrites the existing requirements.txt

      # Step 5: Configure Git for committing
      - name: Configure Git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and push if requirements.txt has changed
      - name: Commit and push changes
        run: |
          git add requirements.txt
          # Check if there are changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "chore: update requirements.txt [skip ci]"
            git push
          else
            echo "No changes to requirements.txt"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
